export const GAZETTE = 'SO:3922(E), Dated: 12th September ,2024';

export const PRODUCTS = [
  { brand: 'SP ROOT POWER', specification: 'Humic Acid 5 % (Powder)', crops: ['Chilli Pepper'], dosage: ['Three foliar application at 0.5 g/l.'], gazette: GAZETTE, composition: ['(i) Humic Acid per cent. by weight minimum 5', '(ii) pH (1 % aq solution) 4.0 – 5.0', '(iii) Specific Gravity 1.0'] },
  { brand: 'SP MAGIC', specification: 'Humic substances 6% (Liquid)', crops: ['Soybean'], dosage: ['Two foliar applications at 1250 ml/ha'], gazette: GAZETTE, composition: ['(i) Humic substances (Source: Brown coal) per cent. by weight, minimum 5', '(ii) Seaweed (Ascophyllum nodosum) extract per cent. by weight, minimum 24', '(iii) Alkaline reagents (anyone or combination of potassium hydroxide, sodium hydroxide, dipotassium hydrogen phosphate, potassium carbonate) per cent. by weight, minimum 5', '(iv) Water per cent. by weight QS', '(v) Total (per cent.) 100'] },
  { brand: 'SP SOIL STRUCTURE', specification: 'Humic acid 19.6 % (Liquid)', crops: ['Tomato'], dosage: ['Two foliar applications at 7.5 litre/ha'], gazette: GAZETTE, composition: ['(i) Humic acid (Source: Leonardite) per cent. by weight, minimum 19.6', '(ii) Hydrogen peroxide per cent. by weight, minimum 0.96', '(iii) Amorphous silica per cent. by weight, minimum 0.04', '(iv) Potassium hydroxide per cent. by weight, minimum 10.3', '(v) Sodium gluconate per cent. by weight, minimum 17.0', '(vi) Sodium hydroxide per cent. by weight, minimum 1.1', '(vii) Water per cent. by weight QS', '(viii) Total (per cent.) 100'] },
  { brand: 'SP BIO BOOSTER', specification: 'Seaweed Extract: Kappaphycus alvarezii 24% (Liquid)', crops: ['Cucumber'], dosage: ['One foliar application at 2 ml/l'], gazette: GAZETTE, composition: ['(i) Total carbohydrate per cent. by weight, minimum 7.5', '(ii) D-Galactose – 4-O- Sulphate per cent. by weight, minimum 6.0', '(iii) pH (minimum) (1:2 aqueous solution) 3.0 – 5.0'] },
  { brand: 'SP BIO PARI', specification: 'Ascophyllum nodosum 7% (Liquid)', crops: ['Tomato'], dosage: ['One soil application as drenching', 'Three foliar applications at 2.5 l/ha'], gazette: GAZETTE, composition: ['(i) Ascophyllum nodosum extract per cent. by weight, minimum 7', '(ii) Methylene carbamide per cent. by weight, minimum as adjuvant 2', '(iii) Benzisothiazolinone per cent by weight, minimum 0.3', '(iv) Water per cent. by weight QS', '(v) Total (per cent.) 100'] },
  { brand: 'SP SUPERGOLD', specification: 'Seaweed (Sargassum wightii) extract 10 % (Liquid)', crops: ['Chilli'], dosage: ['Four foliar application at 2000 ml/ha'], gazette: GAZETTE, composition: ['(i) Seaweed (Sargassum wightii) extract per cent. by weight, minimum 10', '(ii) Water per cent. by weight QS', '(iii) Total (per cent.) 100'] },
  { brand: 'SP SUPER UPTAKE', specification: 'Seaweed (Ascophyllum nodosum) extract 99.52 % (Liquid)', crops: ['Grapes', 'Cotton'], dosage: ['Grapes: Three foliar applications at 300 ml/ha', 'Cotton: Three foliar applications at 300 ml/ha'], gazette: GAZETTE, composition: ['(i) Seaweed (Ascophyllum nodosum) extract per cent. by weight, minimum 99.52', '(ii) Sodium metabisulphite/ potassium sorbate per cent. by weight, minimum 0.48', '(iii) Total (per cent.) 100'] },
  { brand: 'SP ULTRACANE SPECIAL', specification: 'Botanical Extract: Adhatoda vasica extract 2% (Liquid)', crops: ['Chilli', 'Tomato'], dosage: ['Chilli: Three foliar applications at 1000 ml/ha', 'Tomato: Three foliar applications at 1250 ml/ha'], gazette: GAZETTE, composition: ['(i) Adhatoda vasica (leaf) extract per cent. by weight, minimum 2', '(ii) N propanol as solvent per cent. weight by volume, maximum 20', '(iii) Vegetable (soybean) oil per cent. weight by volume, maximum 78', '(iv) Total (per cent.) 100'] },
  { brand: 'SP PLANT FLOWERING', specification: 'Cytokinin (Zea mays kernel) 0.2% (Liquid)', crops: ['Capsicum'], dosage: ['Three foliar applications at 750 ml/ha'], gazette: GAZETTE, composition: ['(i) Cytokinin (Source: Zea mays kernel) per cent. weight by volume, minimum 0.02', '(ii) Potassium sorbate per cent. weight by volume, minimum 0.001', '(iii) Demineralized aqua per cent. by weight QS', '(iv) Total (per cent.) 100'] },
  { brand: 'SP TARZAN', specification: 'Mixed Formulation: Mixture of seaweed extract and algal extract (Liquid)', crops: ['Brinjal'], dosage: ['Two foliar applications at 500 mL/ha'], gazette: GAZETTE, composition: ['(i) Sargassum wightii extract per cent. weight by volume, minimum 2.2', '(ii) Arthrospira platensis extract per cent. weight by volume, minimum 3.3', '(iii) Water per cent. by weight QS', '(iv) Total (per cent.) 100'] },
  { brand: 'SP BOSS', specification: 'Mixture of Humic acid and Seaweed extract (Liquid)', crops: ['Tomato'], dosage: ['Three foliar applications at 1.25 l/ha'], gazette: GAZETTE, composition: ['(i) Humic acid (Source: Leonardite) per cent. weight by volume, minimum 6', '(ii) Kappaphycus alvarezii and Sargassum swartzii in ratio of 1:1; liquid concentrate per cent. volume by volume, minimum 4', '(iii) Propylparaben per cent. weight by volume, minimum as preservative 0.02', '(iv) Methyl paraben per cent. weight by volume, minimum as preservative 0.2', '(v) Potassium benzoate per cent. weight by volume, minimum 0.10', '(vi) Water per cent. by weight 89.68', '(vii) Total (per cent.) 100'] },
  { brand: 'SP SUKRUTH', specification: 'Mixture of Botanical extract and Seaweed extract (Liquid)', crops: ['Tomato'], dosage: ['Three foliar applications at 3.75 l/ha'], gazette: GAZETTE, composition: ['(i) Musa acuminata pseudostem per cent. by weight, minimum 75', '(ii) Sargassum tenerrimum per cent. by weight, minimum 4', '(iii) Polysorbate 80 per cent. by weight, minimum 0.2', '(iv) Water per cent. by weight QS', '(v) Total (per cent.) 100'] },
  { brand: 'SP RUDRA', specification: 'Mixture of Seaweed extract, Protein Hydrolysate and Humic acid (Liquid)', crops: ['Onion', 'Paddy', 'Potato', 'Chilli'], dosage: ['Onion: Three foliar sprays at 500 ml/ha', 'Paddy: Three foliar sprays at 500 ml/ha', 'Potato: Three foliar sprays at 500 ml/ha', 'Chilli: Three foliar sprays at 500 ml/ha'], gazette: GAZETTE, composition: ['(i) Seaweed extract (Ascophyllum nodosum) per cent. by weight, maximum 10.0', '(ii) Protein hydrolysate derived from defatted soy flour by enzymatic (papain) hydrolysis per cent. by weight, minimum 12.0', '(iii) Humic acid (source: Leonardite) per cent. by weight, minimum 0.5', '(iv) Polysorbate 80 per cent. by weight, minimum 2', '(v) Water per cent. by weight QS', '(vi) Total (per cent.) 100'] },
  { brand: 'SP BOOMI BOOSTER', specification: 'Sargassum tenerrimum 1.2% (Granules)', crops: ['Tomato', 'Rice'], dosage: ['Rice: Two soil applications at 15 kg/ha', 'Tomato: Two soil applications at 17.5 kg/ha'], gazette: GAZETTE, composition: ['(i) Seaweed extract (Sargassum tenerrimum) per cent. by weight, minimum 1.2', '(ii) Diethylene glycol per cent. by weight, minimum 0.15', '(iii) Nonylphenol ethoxylate per cent. by weight, minimum 0.10', '(iv) Bentonite granules per cent. by weight 98.55', '(v) Total (per cent.) 100'] },
  { brand: 'SP TIGER', specification: 'Humate 7.15 % (Liquid)', crops: ['Rice', 'Chilli'], dosage: ['Rice: Three foliar applications at 1250 ml/ha', 'Chilli: Three foliar applications at 1500 ml/ha'], gazette: GAZETTE, composition: ['(i) Potassium humate per cent. by weight, minimum 7.15', '(ii) Water per cent. by weight QS', '(iii) Total (per cent.) 100'] },
  { brand: 'SP GROWTH BOOSTER', specification: 'Bacterial biomass hydrolysate (Amino acids 2%) (Liquid)', crops: ['Grape', 'Chilli', 'Soyabean', 'Cotton'], dosage: ['Grape: Four foliar sprays at 1.25 l/ha to 2.0 l/ha depending on canopy size', 'Chilli: Three foliar applications at 3.75 l/ha', 'Soyabean: Three foliar applications at 2.5 l/ha', 'Cotton: Three foliar applications at 2.5 l/ha'], gazette: GAZETTE, composition: ['(i) Amino acids derived from enzymatic (Alkaline Protease) hydrolysis of bacterial biomass (Methylococcus capsulatus) per cent. by weight, minimum 2', '(ii) Water per cent. by weight QS', '(iii) Total (per cent.) 100'] },
  { brand: 'SP SIZER', specification: 'Protein Hydrolysate 18% (Animal source) (Liquid)', crops: ['Paddy', 'Chilli', 'Tomato', 'Grape', 'Cotton', 'Blackgram'], dosage: ['Paddy: Two foliar applications at 1200 ml/ha', 'Chilli: Four foliar applications at 1000 ml/ha', 'Tomato: Three foliar applications at 1000 ml/ha', 'Grape: Two foliar applications at 1000 ml/ha', 'Cotton: One foliar application at 625 ml/ha', 'Black gram: Three foliar applications at 750 ml/ha'], gazette: GAZETTE, composition: ['(i) Protein hydrolysate derived through combination of enzymatic (Exo and endo proteases) and mild acid (HCl) hydrolysis of maize and soybean seed protein (9:1 ratio) per cent. by weight, minimum 18', '(ii) Water per cent. by weight 82', '(iii) Total (per cent.) 100'] },
  { brand: 'SP POWERGOLD', specification: 'L-Pyroglutamic acid (Pidolic acid) 10 % (Liquid)', crops: ['Grape'], dosage: ['Four foliar applications at 1000 ml/ha'], gazette: GAZETTE, composition: ['(i) L-Pyroglutamic acid (Pidolic acid) per cent. by weight, minimum 10.0', '(ii) Organosulfur compound per cent. by weight, minimum 8.8', '(iii) Carboxylic acid per cent. by weight, minimum 1.0', '(iv) Proline derivative per cent. by weight, minimum 9.0', '(v) Amino alcohol (stabilizer) per cent. by weight, minimum 0.20', '(vi) Polyglycolide (surfactant) per cent. by weight, minimum 0.01', '(vii) Glycerine per cent. by weight, minimum 0.43', '(viii) Water per cent. by weight QS', '(ix) Total (per cent.) 100'] },
  { brand: 'SP NANOPOWER', specification: 'Homobrassinolide- 0.04% (Liquid)', crops: ['Tea', 'Grape', 'Groundnut', 'Soybean', 'Paddy', 'Cotton', 'Tomato'], dosage: ['Tea: Three foliar applications at 250 ml/ha', 'Grape: Two foliar applications at 1000 ml/ha', 'Groundnut: Two foliar applications at 250 ml/ha', 'Soybean: Two foliar applications at 250 ml/ha', 'Paddy: Two foliar applications at 250 ml/ha', 'Cotton: Two foliar applications at 250 ml/ha', 'Tomato: Two foliar applications at 250 ml/ha'], gazette: GAZETTE, composition: ['(i) Homobrassinolide (Source: Synthetic) per cent. by weight, minimum 0.04', '(ii) Polysorbate 20 as adjuvant per cent. by weight, minimum 2.00', '(iii) 4- Nonylphenol ethoxylated per cent. by weight, minimum 2.00', '(iv) Isopropyl alcohol per cent. by weight QS', '(v) Total (per cent.) 100'] },
  { brand: 'SP BOOMI SHAKTHI', specification: 'Seaweed (Sargassum wightii) extract 5 % (Granuler)', crops: ['Chilli'], dosage: ['Four soil applications at 20 kg/ha'], gazette: GAZETTE, composition: ['(i) Seaweed (Sargassum wightii) extract per cent. by weight, minimum 5', '(ii) Bentonite per cent. by weight QS', '(iii) Total (per cent.) 100'] },
];

export const SLUG_TO_BRAND = {
  'SP ROOT POWER': 'SP ROOT POWER',
  'SP%20ROOT%20POWER': 'SP ROOT POWER',
  'HUMICID': 'SP ROOT POWER',
};

export function findProductBySlug(slug) {
  const decoded = decodeURIComponent(slug);
  const normalized = decoded.replace(/\+/g, ' ');
  const brand = SLUG_TO_BRAND[normalized] || SLUG_TO_BRAND[slug] || normalized;
  const found = PRODUCTS.find(p => p.brand.toUpperCase() === brand.toUpperCase());
  return found || PRODUCTS[0];
}

export function findProductByBrand(brand) {
  return PRODUCTS.find(p => p.brand === brand) || PRODUCTS[0];
}